--------------------------------------------------------
-- Archivo creado  - sábado-abril-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PELICULAS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PELICULAS" 
   (	"ID" NUMBER, 
	"TITULO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANIO" NUMBER(4,0), 
	"DIRECTOR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"GENERO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SINOPSIS" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("SINOPSIS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ADMIN.PELICULAS
SET DEFINE OFF;

Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('1','Matrix','1999','Lana Wachowski','Ciencia Ficción');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('2','El Padrino','1972','Francis Ford Coppola','Drama');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('3','Inception','2010','Christopher Nolan','Ciencia Ficción');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('4','Titanic','1997','James Cameron','Romance');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('5','Parásito','2019','Bong Joon-ho','Thriller');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('6','One Piece','1995','Eichiro Oda','Anime');
Insert into ADMIN.PELICULAS (ID,TITULO,ANIO,DIRECTOR,GENERO) values ('7','Interstellar','2014','Christopher Nolan','Ciencia Ficción');
--------------------------------------------------------
--  DDL for Index SYS_C0029625
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0029625" ON "ADMIN"."PELICULAS" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PELICULAS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PELICULAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
